[package]
name = "grayarea"
version = "0.1.0"
authors = ["Maksym Vorobiov <maxim.vorobjov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["ws"]
ws = ["tungstenite", "tokio-tungstenite", "tokio", "url", "futures"]

[workspace]
members = ["grayarea-lib", "polo-consumer"]

[dependencies]
wasmer-runtime = "0.11"
wasmer-runtime-core = "0.11"
wasmer-wasi = "0.11"
tungstenite = { version="0.9", optional=true }
tokio-tungstenite = { git="https://github.com/dbcfd/tokio-tungstenite", branch="tokio2-released", features=["tls"], optional=true }
tokio = { version="0.2", optional=true, features=["macros"] }
url = { version="2.1", optional=true, features=["serde"] }
futures = { version="0.3", optional=true }
structopt = { version="0.3", default_features=false }
serde = { version="1", features=["derive"] }
serde_yaml = "0.8"
anyhow = "1"